# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources_wel import *

class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 281, 431))
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 231, 430))
        self.frame.setStyleSheet("border-image: url(:/images/images/images/khoidong.png);\n"
"border-top-left-radius: 50px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(230, 0, 51, 430))
        self.frame_2.setStyleSheet("background-image: url(:/images/images/images/5172658.jpg);\n"
"border-bottom-right-radius: 50px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 0, 16, 271))
        self.label.setStyleSheet("background: none;\n"
"font: 8pt \"Sitka Small\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">W</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">E</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">L</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">L</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">C</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">O</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">M</span></p><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">E</span></p></body></html>"))

